### ISSUE TITLE
[Platfrom]The tasks for Rsdoctor UI optimizations

### ISSUE THREAD

**Issue by easy1090** [web-infra-dev/rsdoctor#10]
This list will be continuously supplemented.
```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rsdoctor/issues/45
- [x] https://github.com/web-infra-dev/rsdoctor/issues/79
- [ ] https://github.com/web-infra-dev/rsdoctor/issues/81
```
