### ISSUE TITLE
[Bug]: When app ues vue-loader, the loader analysis lack some files which compile by vue-loader.

### ISSUE THREAD

**Issue by easy1090** [web-infra-dev/rsdoctor#38]
### Version

```sh
@rsdoctor/webpack-plugin@0.0.1
```

### Details

In vue app, when app ues vue-loader, the loader analysis lack some files which compile by vue-loader.

### Reproduce Steps

1. Init an vue app by modern-js
2. Add @rsdoctor/webpack-plugin
3. Run build with @rsdoctor/webpack-plugin
4. the report of loader analysis just have some vue file
```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rsdoctor/pull/467
- [x] 排查 vue-loader 和 rsdoctor loader proxy 冲突的原因。
- [x] [bug] rspack:lightcss-loader can not be analyzed.
- [x] Add examples and tests for the vue analysis
```
