### ISSUE TITLE
[Platform] Create report platform packages named @rsdoctor/components and @rsdoctor/client

### ISSUE THREAD

**Issue by easy1090** [web-infra-dev/rsdoctor#6]
After the Rsdoctor finishes execution, a reporting and display platform is required.
```[tasklist]
### Tasks
- [ ] https://github.com/web-infra-dev/rsdoctor/issues/25
- [ ] https://github.com/web-infra-dev/rsdoctor/issues/36
- [ ] https://github.com/web-infra-dev/rsdoctor/issues/39
- [ ] https://github.com/web-infra-dev/rsdoctor/issues/40
- [ ] https://github.com/web-infra-dev/rsdoctor/issues/51
- [ ] https://github.com/web-infra-dev/rsdoctor/issues/52
- [ ] https://github.com/web-infra-dev/rsdoctor/issues/26
- [ ] https://github.com/web-infra-dev/rsdoctor/issues/41
```
